openapi: 3.0.0
info:
  title: bAmpli API
  description: Business Amplifier API
  contact:
    name: Jose Motta
    url: http://bampli.com
    email: josemotta@bampli.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0-oas3
servers:
- url: https://virtserver.swaggerhub.com/motta/bampli/1.0.0-oas3
  description: SwaggerHub API Auto Mocking
- url: https://virtserver.swaggerhub.com/motta/bampli/1.0.0
tags:
- name: Company
  description: Company operations
- name: Facility
  description: Facility operations
- name: Cyclo
  description: Cyclo operations
paths:
  /company:
    get:
      tags:
      - Company
      summary: Get Company
      description: |
        Search for an available Company in the system
      operationId: get_company
      parameters:
      - name: searchString
        in: query
        description: pass an optional search string for looking up inventory
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: skip
        in: query
        description: number of records to skip for pagination
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
          format: int32
      - name: limit
        in: query
        description: maximum number of records to return
        required: false
        style: form
        explode: true
        schema:
          maximum: 10
          minimum: 0
          type: integer
          format: int32
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company'
                x-content-type: application/json
        "400":
          description: bad input parameter
      x-swagger-router-controller: Company
      x-openapi-router-controller: swagger_server.controllers.company_controller
    post:
      tags:
      - Company
      summary: Add Company
      description: Adds a Company to the system
      operationId: add_company
      requestBody:
        description: Company item to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Company'
      responses:
        "201":
          description: item created
        "400":
          description: invalid input, object invalid
        "409":
          description: an existing item already exists
      x-openapi-router-controller: swagger_server.controllers.company_controller
  /product:
    get:
      tags:
      - Company
      summary: Get Product
      description: |
        Search for an available Product in the system
      operationId: get_product
      parameters:
      - name: searchString
        in: query
        description: pass an optional search string for looking up inventory
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: skip
        in: query
        description: number of records to skip for pagination
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
          format: int32
      - name: limit
        in: query
        description: maximum number of records to return
        required: false
        style: form
        explode: true
        schema:
          maximum: 10
          minimum: 0
          type: integer
          format: int32
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
                x-content-type: application/json
        "400":
          description: bad input parameter
      x-swagger-router-controller: Company
      x-openapi-router-controller: swagger_server.controllers.company_controller
    post:
      tags:
      - Company
      summary: Add Product
      description: Adds a Product to the system
      operationId: add_product
      requestBody:
        description: Product item to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        "201":
          description: item created
        "400":
          description: invalid input, object invalid
        "409":
          description: an existing item already exists
      x-openapi-router-controller: swagger_server.controllers.company_controller
  /facility:
    get:
      tags:
      - Facility
      summary: Get Facility
      description: |
        Search for an available Facility in the system
      operationId: get_facility
      parameters:
      - name: searchString
        in: query
        description: pass an optional search string for looking up inventory
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: skip
        in: query
        description: number of records to skip for pagination
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
          format: int32
      - name: limit
        in: query
        description: maximum number of records to return
        required: false
        style: form
        explode: true
        schema:
          maximum: 10
          minimum: 0
          type: integer
          format: int32
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Facility'
                x-content-type: application/json
        "400":
          description: bad input parameter
      x-swagger-router-controller: Facility
      x-openapi-router-controller: swagger_server.controllers.facility_controller
    post:
      tags:
      - Facility
      summary: Add Facility
      description: Adds a Facility to the system
      operationId: add_facility
      requestBody:
        description: Facility item to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Facility'
      responses:
        "201":
          description: item created
        "400":
          description: invalid input, object invalid
        "409":
          description: an existing item already exists
      x-openapi-router-controller: swagger_server.controllers.facility_controller
  /wip:
    get:
      tags:
      - Facility
      summary: Get Wip
      description: |
        Search for an available Wip in the system
      operationId: search_wip
      parameters:
      - name: searchString
        in: query
        description: pass an optional search string for looking up wip
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: skip
        in: query
        description: number of records to skip for pagination
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
          format: int32
      - name: limit
        in: query
        description: maximum number of records to return
        required: false
        style: form
        explode: true
        schema:
          maximum: 50
          minimum: 0
          type: integer
          format: int32
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Wip'
                x-content-type: application/json
        "400":
          description: bad input parameter
      x-openapi-router-controller: swagger_server.controllers.facility_controller
    post:
      tags:
      - Facility
      summary: Add Wip
      description: Adds a Wip to the system
      operationId: add_wip
      requestBody:
        description: Wip item to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Wip'
      responses:
        "201":
          description: item created
        "400":
          description: invalid input, object invalid
        "409":
          description: an existing item already exists
      x-openapi-router-controller: swagger_server.controllers.facility_controller
  /cyclo:
    get:
      tags:
      - Cyclo
      summary: Get Cyclo
      description: |
        Search for an available Cyclo in the system
      operationId: get_cyclo
      parameters:
      - name: searchString
        in: query
        description: pass an optional search string for looking up inventory
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: skip
        in: query
        description: number of records to skip for pagination
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
          format: int32
      - name: limit
        in: query
        description: maximum number of records to return
        required: false
        style: form
        explode: true
        schema:
          maximum: 10
          minimum: 0
          type: integer
          format: int32
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cyclo'
                x-content-type: application/json
        "400":
          description: bad input parameter
      x-swagger-router-controller: Cyclo
      x-openapi-router-controller: swagger_server.controllers.cyclo_controller
    post:
      tags:
      - Cyclo
      summary: Add Cyclo
      description: Adds a Cyclo to the system
      operationId: add_cyclo
      requestBody:
        description: Cyclo item to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cyclo'
      responses:
        "201":
          description: item created
        "400":
          description: invalid input, object invalid
        "409":
          description: an existing item already exists
      x-openapi-router-controller: swagger_server.controllers.cyclo_controller
  /stage:
    get:
      tags:
      - Cyclo
      summary: Get Stage
      description: |
        Search for an available Stage in the system
      operationId: get_stage
      parameters:
      - name: searchString
        in: query
        description: pass an optional search string for looking up inventory
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: skip
        in: query
        description: number of records to skip for pagination
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
          format: int32
      - name: limit
        in: query
        description: maximum number of records to return
        required: false
        style: form
        explode: true
        schema:
          maximum: 10
          minimum: 0
          type: integer
          format: int32
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Stage'
                x-content-type: application/json
        "400":
          description: bad input parameter
      x-swagger-router-controller: Cyclo
      x-openapi-router-controller: swagger_server.controllers.cyclo_controller
    post:
      tags:
      - Cyclo
      summary: Add Stage
      description: Adds a Stage to the system
      operationId: add_stage
      requestBody:
        description: Stage item to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Stage'
      responses:
        "201":
          description: item created
        "400":
          description: invalid input, object invalid
        "409":
          description: an existing item already exists
      x-openapi-router-controller: swagger_server.controllers.cyclo_controller
  /task:
    get:
      tags:
      - Cyclo
      summary: Get Task
      description: |
        Search for an available Task in the system
      operationId: get_task
      parameters:
      - name: searchString
        in: query
        description: pass an optional search string for looking up inventory
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: skip
        in: query
        description: number of records to skip for pagination
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
          format: int32
      - name: limit
        in: query
        description: maximum number of records to return
        required: false
        style: form
        explode: true
        schema:
          maximum: 10
          minimum: 0
          type: integer
          format: int32
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
                x-content-type: application/json
        "400":
          description: bad input parameter
      x-swagger-router-controller: Cyclo
      x-openapi-router-controller: swagger_server.controllers.cyclo_controller
    post:
      tags:
      - Cyclo
      summary: Add Task
      description: Adds a Task to the system
      operationId: add_task
      requestBody:
        description: Task item to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        "201":
          description: item created
        "400":
          description: invalid input, object invalid
        "409":
          description: an existing item already exists
      x-openapi-router-controller: swagger_server.controllers.cyclo_controller
components:
  schemas:
    Product:
      required:
      - company
      - lastModified
      - name
      - product
      type: object
      properties:
        product:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: Fast Ethernet Adapter 10/100/1000 Mbps
        lastModified:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        company:
          $ref: '#/components/schemas/Company'
      description: bAmpli Product
      example:
        product: d290f1ee-6c54-4b01-90e6-d701748f0851
        name: Fast Ethernet Adapter 10/100/1000 Mbps
        company:
          phone: +55 21 99123-4567
          name: ACME Corporation
          company: d290f1ee-6c54-4b01-90e6-d701748f0851
          lastModified: 2016-08-29T09:12:33.001Z
          homePage: https://www.acme-corp.com.br
        lastModified: 2016-08-29T09:12:33.001Z
    Wip:
      required:
      - facility
      - lastModified
      - name
      - wip
      type: object
      properties:
        wip:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: Widget Adapter
        lastModified:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        facility:
          $ref: '#/components/schemas/Facility'
      description: bAmpli Work-in-Process
      example:
        name: Widget Adapter
        lastModified: 2016-08-29T09:12:33.001Z
        facility:
          name: P&Q Facility
          company:
            phone: +55 21 99123-4567
            name: ACME Corporation
            company: d290f1ee-6c54-4b01-90e6-d701748f0851
            lastModified: 2016-08-29T09:12:33.001Z
            homePage: https://www.acme-corp.com.br
          lastModified: 2016-08-29T09:12:33.001Z
          facility: d290f1ee-6c54-4b01-90e6-d701748f0851
        wip: d290f1ee-6c54-4b01-90e6-d701748f0851
    Task:
      required:
      - lastModified
      - name
      - stage
      - task
      type: object
      properties:
        task:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: Fast Ethernet Adapter 10/100/1000 Mbps
        lastModified:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        stage:
          $ref: '#/components/schemas/Stage'
      description: bAmpli Task
      example:
        task: d290f1ee-6c54-4b01-90e6-d701748f0851
        stage:
          stage: d290f1ee-6c54-4b01-90e6-d701748f0851
          name: Fast Ethernet Adapter 10/100/1000 Mbps
          lastModified: 2016-08-29T09:12:33.001Z
          cyclo:
            name: Cyclo P&Q
            company:
              phone: +55 21 99123-4567
              name: ACME Corporation
              company: d290f1ee-6c54-4b01-90e6-d701748f0851
              lastModified: 2016-08-29T09:12:33.001Z
              homePage: https://www.acme-corp.com.br
            cyclo: d290f1ee-6c54-4b01-90e6-d701748f0851
            lastModified: 2016-08-29T09:12:33.001Z
        name: Fast Ethernet Adapter 10/100/1000 Mbps
        lastModified: 2016-08-29T09:12:33.001Z
    Stage:
      required:
      - cyclo
      - lastModified
      - name
      - stage
      type: object
      properties:
        stage:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: Fast Ethernet Adapter 10/100/1000 Mbps
        lastModified:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        cyclo:
          $ref: '#/components/schemas/Cyclo'
      description: bAmpli Stage
      example:
        stage: d290f1ee-6c54-4b01-90e6-d701748f0851
        name: Fast Ethernet Adapter 10/100/1000 Mbps
        lastModified: 2016-08-29T09:12:33.001Z
        cyclo:
          name: Cyclo P&Q
          company:
            phone: +55 21 99123-4567
            name: ACME Corporation
            company: d290f1ee-6c54-4b01-90e6-d701748f0851
            lastModified: 2016-08-29T09:12:33.001Z
            homePage: https://www.acme-corp.com.br
          cyclo: d290f1ee-6c54-4b01-90e6-d701748f0851
          lastModified: 2016-08-29T09:12:33.001Z
    Cyclo:
      required:
      - company
      - cyclo
      - lastModified
      - name
      type: object
      properties:
        cyclo:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: Cyclo P&Q
        lastModified:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        company:
          $ref: '#/components/schemas/Company'
      description: bAmpli Cyclo
      example:
        name: Cyclo P&Q
        company:
          phone: +55 21 99123-4567
          name: ACME Corporation
          company: d290f1ee-6c54-4b01-90e6-d701748f0851
          lastModified: 2016-08-29T09:12:33.001Z
          homePage: https://www.acme-corp.com.br
        cyclo: d290f1ee-6c54-4b01-90e6-d701748f0851
        lastModified: 2016-08-29T09:12:33.001Z
    Facility:
      required:
      - company
      - facility
      - lastModified
      - name
      type: object
      properties:
        facility:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: P&Q Facility
        lastModified:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        company:
          $ref: '#/components/schemas/Company'
      description: bAmpli Facility
      example:
        name: P&Q Facility
        company:
          phone: +55 21 99123-4567
          name: ACME Corporation
          company: d290f1ee-6c54-4b01-90e6-d701748f0851
          lastModified: 2016-08-29T09:12:33.001Z
          homePage: https://www.acme-corp.com.br
        lastModified: 2016-08-29T09:12:33.001Z
        facility: d290f1ee-6c54-4b01-90e6-d701748f0851
    Company:
      required:
      - company
      - lastModified
      - name
      properties:
        company:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: ACME Corporation
        lastModified:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        homePage:
          type: string
          format: url
          example: https://www.acme-corp.com.br
        phone:
          type: string
          example: +55 21 99123-4567
      description: bAmpli Company
      example:
        phone: +55 21 99123-4567
        name: ACME Corporation
        company: d290f1ee-6c54-4b01-90e6-d701748f0851
        lastModified: 2016-08-29T09:12:33.001Z
        homePage: https://www.acme-corp.com.br

